version: "3.3"
services:
  app:
    build: .
    # environment:
    #   - PROCESSES=$PROCESSES
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - app_setup
  mongo:
    image: mongo:5
    hostname: mongo.devrepl
    networks:
      default:
         aliases:
            - mongo.devrepl
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    command:
      - --storageEngine
      - wiredTiger
      - --replSet
      - devrepl
    #restart: always
  app_setup:
    image: mongo:5
    command: sh -c "sleep 5 && mongo mongo.devrepl:27017 --eval 'rs.initiate()'"
    links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongodb:
