version: "3.3"
services:
  app:
    build: .
    # environment:
    #   - PROCESSES=$PROCESSES
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
  db:
    image: mongo:4.4
    volumes:
      - ./db:/data/db
